Add Github Authentication and Header
rss-com-lab/mentor-dashboard pull request #11
Opened 2019-04-12 21:58 UTC by uniorunr

issue #9
 - implemented GitHub Authentication via Firebase;
 - added Header;

The live version of App - https://rss-mentor-dashboard-2185d.firebaseapp.com/

2019-04-15 11:17 UTC, davojta commented on src/components/Dashboard/parser.js
> +  } if (score && getTaskStatus(currentTaskName, dataObj) === 'Checking') {
у нас разве нету уже prettier ? чтобы форматировать нормально?
if должен быть после {

2019-04-15 11:22 UTC, davojta commented on src/components/Header/HeaderSelect/HeaderSelect.js
> +      if (user && isMentor(user.displayName, mentorsList)) {
isMentor(user.displayName, mentorsList) is better to put to separate var

2019-04-15 11:23 UTC, davojta commented on src/firebase/firebase.js
> +      throw new Error(error);
it is better to create a normal error  and add console.error('logout error', e);

2019-04-15 11:24 UTC, davojta requested changes
Need to adjust some code style issues

2019-04-15 17:11 UTC, uniorunr commented
I've fixed issues

2019-04-16 07:58 UTC, davojta commented on src/components/Dashboard/parser.js
> +  }
thanks!

2019-04-16 07:59 UTC, davojta commented on src/components/Header/HeaderSelect/HeaderSelect.js
> +      if (user && mentor) {
+1

2019-04-16 08:00 UTC, davojta approved these changes
LGTM!

2019-04-16 08:14 UTC, merged